resources:
  jobs:
    Production_Streaming_Transactions:
      name: Production Streaming Transactions
      tasks:
        - task_key: Feature_Engineering
          notebook_task:
            notebook_path: "/Repos/stephanie.rivera@databricks.com/Databricks-ML-in-Action/\
              Chapter 7: Productionizing ML on Databricks/Project: Streaming
              Transactions/CH7-10-Production Feature Engineering With Spark
              Structured Streaming"
            source: WORKSPACE
          existing_cluster_id: 1211-220000-yxqdea6c
        - task_key: Generate_Data
          notebook_task:
            notebook_path: "/Repos/stephanie.rivera@databricks.com/Databricks-ML-in-Action/\
              Chapter 7: Productionizing ML on Databricks/Project: Streaming
              Transactions/CH7-08-Production Generating Records"
            source: WORKSPACE
          existing_cluster_id: 1211-220000-yxqdea6c
        - task_key: JSON_to_Delta
          notebook_task:
            notebook_path: "/Repos/stephanie.rivera@databricks.com/Databricks-ML-in-Action/\
              Chapter 7: Productionizing ML on Databricks/Project: Streaming
              Transactions/CH7-09-Production Auto Loader"
            source: WORKSPACE
          existing_cluster_id: 1211-220000-yxqdea6c
      parameters:
        - name: feature_history_table_name
          default: transaction_count_history
        - name: feature_table_name
          default: transaction_count_ft
        - name: raw_table_name
          default: prod_transactions
